module.exports = [
  {
    title: "Mukundara Hills Tiger Reserve Brief Note",
    slug: "ntca-brief-note",
    category: "Core official",
    authority: "National Tiger Conservation Authority (NTCA)",
    year: "Not stated",
    summary: "Official high-level overview of Mukundara Hills Tiger Reserve in the national tiger conservation context.",
    sourcePageUrl: "https://ntca.gov.in/",
    sourcePdfUrl: "https://ntca.gov.in/assets/uploads/briefnote/mukundara.pdf",
    localPdfPath: "/assets/docs/ntca-mukundara-brief-note.pdf",
    hosted: false,
  },
  {
    title: "Mukundara Hills Tiger Reserve Notification",
    slug: "moefcc-notification",
    category: "Legal and notification",
    authority: "Ministry of Environment, Forest and Climate Change (MoEFCC)",
    year: "2020",
    summary: "Government notification defining legal status and notified reserve details.",
    sourcePageUrl: "https://moef.gov.in/",
    sourcePdfUrl: "https://moef.gov.in/uploads/2020/12/mukundra-1.pdf",
    localPdfPath: "/assets/docs/moefcc-mukundara-notification.pdf",
    hosted: false,
  },
  {
    title: "Tiger Conservation Plan (TCP) — Mukundara Hills Tiger Reserve",
    slug: "tiger-conservation-plan",
    category: "Planning and management",
    authority: "Wildlife Institute of India (MEE-TR portal)",
    year: "2020–2030 cycle",
    summary: "Core planning document covering habitat management, protection strategy, eco-development and monitoring framework.",
    sourcePageUrl: "https://mee-tr.wii.gov.in/",
    sourcePdfUrl: "https://mee-tr.wii.gov.in/Home/DownloadFilenew?filePath=~%5CUploadedFiles%5CMukundara_Hills_Tiger_Reserve%5CTCP_CTR%5CTCP_Mukundara_Hills.pdf",
    localPdfPath: "/assets/docs/tcp-mukundara-hills.pdf",
    hosted: false,
  },
  {
    title: "Reptiles & Amphibians of Mukundara Hills Tiger Reserve",
    slug: "reptiles-amphibians-guide",
    category: "Biodiversity references",
    authority: "Rajasthan Forest Department",
    year: "Not stated",
    summary: "Taxa-focused field reference used for biodiversity education and baseline species documentation.",
    sourcePageUrl: "https://forest.rajasthan.gov.in/",
    sourcePdfUrl: "https://forest.rajasthan.gov.in/content/dam/raj/forest/ForestDepartment/PDFs/Preliminary-Birds-guide-/Reptiles%20%26%20Amphibians%20book%20of%20MHTR0.pdf",
    localPdfPath: "/assets/docs/rfd-reptiles-amphibians-mhtr.pdf",
    hosted: false,
  },
];
